### ISSUE TITLE
Error transforming when using spread attribute on server

### ISSUE THREAD

**Issue by zimok** [SimonDegraeve/node-cjsx#3]
I'm getting this error while trying to require `.cjsx` file that uses new spread attribute syntax for transfering props:

    <div {... this.props}>hello</div>

`Error: Error transforming /Users/../.cjsx from CJSX: [stdin]:14:5: error: unexpected <`
    `<div {... this.props}>`

I'm using node-cjsx 0.1.2 on server with:

    require('node-cjsx').transform()

If i try to transform the file directly, using `cjsx-transform`, everything is fine.
Any idea why this is happening with node-cjsx only?

**Comment by zimok** [comment]
I just created this test case:

1. test-comp.cjsx
    module.exports
        render: ->
            <div {... this.props}>hello</div>

1. test-server.coffee
    require('node-cjsx').transform()
    require('./test-comp.cjsx')

then launched

    coffee test-server.coffee

and got that error:

    Error transforming...

**Comment by SimonDegraeve** [comment]
Done, updated deps and published to npm.

**Comment by zimok** [comment]
tnx
